# Generated by Django 4.1.7 on 2023-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='base_images')),
                ('name', models.CharField(default='', max_length=50)),
                ('position', models.CharField(choices=[('1', 'Главный тренер'), ('2', 'Дежурный тренер'), ('3', 'Тренер по единоборствам'), ('4', 'Персональный тренер'), ('5', 'Тренер груповых занятий'), ('6', 'Тренер стажер')], default='4', max_length=1)),
            ],
        ),
    ]
