# Generated by Django 4.1.7 on 2023-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerinfo',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
