# Generated by Django 4.1.7 on 2023-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0002_trainerinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerinfo',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='trainerinfo',
            name='picture',
            field=models.FileField(upload_to='trainers_photos'),
        ),
    ]
