# Generated by Django 4.1.7 on 2023-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesql',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
