# Generated by Django 4.1.7 on 2023-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
